- alias: 'Change bar shelf light state when bar lights state changes'
  trigger:
    platform: state
    entity_id: switch.basement_bar_lights
  action:
    service_template: >
      {% if is_state('switch.basement_bar_lights', 'off') %}
        switch.turn_off
      {% else %}
        switch.turn_on
      {% endif %}
    entity_id: switch.basement_bar_wall_lights

- alias: 'Enable tree lights when sun sets'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.living_room_tree_lights

- alias: 'Disable tree lights at 23:00'
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.living_room_tree_lights
