- platform: tplink
  host: 192.168.2.115
  name: Basement Bar Lights
  scan_interval: 1

- platform: tplink
  host: 192.168.2.136
  name: Basement Bar Wall Lights

- platform: tplink
  host: 192.168.1.119
  name: Living Room Tree Lights
