- id: '1657221458522'
  alias: Lock Garage Door
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: device
    device_id: b9d808371d6bdd67d224050a4de2e464
    domain: lock
    entity_id: lock.garage_door_interior
    type: is_unlocked
  action:
  - device_id: b9d808371d6bdd67d224050a4de2e464
    domain: lock
    entity_id: lock.garage_door_interior
    type: lock
  mode: single
- id: '1657806714232'
  alias: Master Bathroom Humidity Control On
  description: ''
  trigger:
  - type: humidity
    platform: device
    device_id: 7b9a1c2435b3a64b13e71705d68adde2
    entity_id: sensor.master_bathroom_temperature_and_humidity_sensor_2805_humidity
    domain: sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
    above: 59.9
  condition:
  - condition: device
    type: is_off
    device_id: 33eb3626910cf8bb28799b560c0f6024
    entity_id: switch.master_bathroom_exhaust_fan
    domain: switch
    for:
      hours: 0
      minutes: 1
      seconds: 0
  action:
  - type: turn_on
    device_id: 33eb3626910cf8bb28799b560c0f6024
    entity_id: switch.master_bathroom_exhaust_fan
    domain: switch
  mode: single
- id: '1657806799442'
  alias: Master Bathroom Humidity Control Off
  description: ''
  trigger:
  - type: humidity
    platform: device
    device_id: 7b9a1c2435b3a64b13e71705d68adde2
    entity_id: sensor.master_bathroom_temperature_and_humidity_sensor_2805_humidity
    domain: sensor
    below: 59.9
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: 33eb3626910cf8bb28799b560c0f6024
    entity_id: switch.master_bathroom_exhaust_fan
    domain: switch
  action:
  - type: turn_off
    device_id: 33eb3626910cf8bb28799b560c0f6024
    entity_id: switch.master_bathroom_exhaust_fan
    domain: switch
  mode: single
