homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:

# Discover some devices automatically
zeroconf:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate

system_health:

mqtt:
  broker: mosquitto

cloud:

backup:

influxdb:
  host: localhost
  username: !secret influx_db_username
  password: !secret influx_db_password
  database: homeassistant
  measurement_attr: entity_id

group: !include groups.yaml

automation: !include automations.yaml
